on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  BuildBinaries:
    name: Build application packages
    strategy:
      matrix:
        runtime: [ linux-x64, osx-x64, win-x64, android ]
        include:
          - runtime: linux-x64
            arch: x64
            os: ubuntu-latest
            build: packageReleaseUberJarForCurrentOS packageDeb

          - runtime: osx-x64
            os: macOS-latest
            build: packageUberJarForCurrentOS packageDmg

          - runtime: win-x64
            os: windows-latest
            build: packageReleaseUberJarForCurrentOS packageReleaseMsi

          - runtime: android
            os: ubuntu-latest
            build: assembleRelease

    runs-on: ${{ matrix.os }}
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        if: ${{ matrix.runtime != 'linux-fedora-x64' }}
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2
        if: ${{ matrix.runtime == 'android' }}

      - name: Build
        uses: gradle/gradle-build-action@v2
        with:
          arguments: >
            ${{ matrix.build }}

      - name: Sign APK
        uses: r0adkll/sign-android-release@v1
        if: ${{ matrix.runtime == 'android' }}
        with:
          releaseDirectory: app/build/outputs/apk/release
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          alias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}

      # Upload runner package tar.gz/zip as artifact
      - name: Publish Artifact
        uses: actions/upload-artifact@v3
        with:
          name: runner-package-${{ matrix.runtime }}
          path: |
            desktop/build/compose/binaries/main/*/
            desktop/build/compose/binaries/main-release/*/
            desktop/build/compose/jars/
            !desktop/build/compose/binaries/main/app/
            ${{ env.SIGNED_RELEASE_FILE }}

        # Upload runner errors
      - name: Upload error logs
        uses: actions/upload-artifact@v3
        if: ${{ failure() }}
        with:
          name: runner-errors-${{ matrix.runtime }}
          path: |
            desktop/build/compose/logs/
  ReleaseBinaries:
    name: Make a release
    needs: [ BuildBinaries ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Download Build Artifacts
        uses: actions/download-artifact@v3

      - uses: ncipollo/release-action@v1
        with:
          artifacts: "*/binaries/main/*/*.*,*/binaries/main-release/*/*.*,*/jars/*.jar,*/app/build/outputs/apk/release/*.apk"
          draft: true
          token: ${{ secrets.TOKEN }}